export default {
  'getting-started': 'Getting Started',
  devices: 'Devices',
  firmware: 'Firmware',
  configurations: 'Configurations',
  policies: 'Policies',
  operations: 'Operations',
  vpn: 'VPN',
  wan: 'WAN',
  'local-users': 'Local Users',
  'security-services': 'Security Services',
  documentation: 'Documentation',
  licensing: 'Licensing',
  alerts: 'Alerts',
  reports: 'Reports',
  'network-map': 'Network Map',
  metrics: 'Metrics',
  benchmark: 'Benchmark',
  compatibility: 'Compatibility',
  compliance: 'Compliance',
  integrations: 'Integrations',
  settings: 'Settings',
  admin: 'Administration',
  security: 'Security & Compliance',
};
