#!/usr/bin/env node
/**
 * Build-time guard for the app's deep links into the Copilot Readiness pages.
 *
 * The SonicSaaS app links each individual readiness check straight to its section here, using an
 * anchor derived from the check's internal ID. Rewording a heading is harmless; deleting or renaming
 * its `[#anchor]` silently breaks a link in the product, and this repo has no link checker to notice.
 *
 * So: `content/m365/_copilot-checks.json` is generated by the app repo
 * (`scripts/emit-copilot-check-manifest.ts`) and lists every check plus the anchor its section must
 * carry. This script asserts each one still exists, and runs as part of `npm run build` — a missing
 * anchor fails the deploy rather than shipping a dead link.
 *
 * Deliberately dependency-free (`node:fs` only): this repo has three devDependencies and no test
 * runner, and adding one for a single assertion is not worth it.
 */
import { readFileSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join, resolve } from "node:path";

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const manifestPath = join(repoRoot, "content", "m365", "_copilot-checks.json");

if (!existsSync(manifestPath)) {
  console.error(`check-anchors: manifest not found at ${manifestPath}`);
  console.error(
    "Regenerate it from the app repo: npx tsx scripts/emit-copilot-check-manifest.ts",
  );
  process.exit(1);
}

const { checks } = JSON.parse(readFileSync(manifestPath, "utf8"));

if (!Array.isArray(checks) || checks.length === 0) {
  console.error(
    "check-anchors: manifest contains no checks — refusing to pass vacuously.",
  );
  process.exit(1);
}

/** Cache file contents so a page with many checks is read once. */
const sources = new Map();
function sourceOf(file) {
  if (!sources.has(file)) {
    const full = join(repoRoot, file);
    sources.set(file, existsSync(full) ? readFileSync(full, "utf8") : null);
  }
  return sources.get(file);
}

const failures = [];

for (const { id, file, anchor } of checks) {
  const src = sourceOf(file);
  if (src === null) {
    failures.push(`${id}: page missing — expected ${file}`);
    continue;
  }
  // Nextra's custom-heading-id syntax: `## Some heading [#the-anchor]`.
  if (!src.includes(`[#${anchor}]`)) {
    failures.push(`${id}: no section anchored [#${anchor}] in ${file}`);
  }
}

if (failures.length > 0) {
  console.error(
    `\ncheck-anchors: ${failures.length} broken in-app documentation link(s):\n`,
  );
  for (const failure of failures) console.error(`  - ${failure}`);
  console.error(
    "\nEach Copilot Readiness check is deep-linked from the product. Add the missing section " +
      "with its [#anchor] heading, or regenerate the manifest from the app repo if a check was " +
      "renamed or removed.\n",
  );
  process.exit(1);
}

console.log(
  `check-anchors: ${checks.length} Copilot Readiness check anchors OK`,
);
